"""Post.icon_id

Revision ID: 7b4028b44355
Revises: a615f4e7d711
Create Date: 2018-06-30 11:37:28.489353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4028b44355'
down_revision = 'a615f4e7d711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('icon_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'icon_id')
    # ### end Alembic commands ###
