"""Initial revision

Revision ID: d90d40ba546f
Revises: 
Create Date: 2018-06-13 20:52:28.792192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90d40ba546f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_relation')
    op.create_index(op.f('ix_posts_poster_uid'), 'posts', ['poster_uid'], unique=False)
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_index('tid_pid', 'posts', ['tid', 'pid'], unique=False)
    op.drop_index('posts_timestamp_idx', table_name='posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('posts_timestamp_idx', 'posts', ['timestamp'], unique=False)
    op.drop_index('tid_pid', table_name='posts')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_index(op.f('ix_posts_poster_uid'), table_name='posts')
    op.create_table('quote_relation',
    sa.Column('quoter_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quotee_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quotee_uid'], ['users.uid'], name='quote_relation_quotee_uid_fkey'),
    sa.ForeignKeyConstraint(['quoter_uid'], ['users.uid'], name='quote_relation_quoter_uid_fkey'),
    sa.PrimaryKeyConstraint('quoter_uid', 'quotee_uid', 'year', name='quote_relation_pkey')
    )
    # ### end Alembic commands ###
