"""users_profile_exists

Revision ID: 60a859376b11
Revises: cbe71cb6749c
Create Date: 2018-06-13 21:08:52.335677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a859376b11'
down_revision = 'cbe71cb6749c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_profile_exists', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_profile_exists')
    # ### end Alembic commands ###
