"""Added naming convention

Revision ID: cbe71cb6749c
Revises: f9bc9b5d8a2c
Create Date: 2018-06-13 21:07:08.771880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe71cb6749c'
down_revision = 'f9bc9b5d8a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
